const menu = [
  {
    id: 1,
    title: 'Private Events',
    category: 'Catering Orders',
    price: 299.99,
    img: './images/image-2.jpeg',
    desc: `Lorem ipsum dolor sit amet, consectetur  incididunt ut labore et dolore magna aliqua Ut enim ad minim veniam quis nostrud. `,
  },
  {
    id: 2,
    title: 'Meal Combo 1',
    category: 'lunch',
    price: 13.99,
    img: './images/image-1.jpeg',
    desc: `Lorem ipsum dolor sit amet, consectetur  incididunt ut labore et dolore magna aliqua Ut enim ad minim veniam quis nostrud.`,
  },
  { 
    id: 3,
    title: 'Meal Combo 2',
    category: 'lunch',
    price: 13.99,
    img: './images/image-1.jpeg',
    desc: `Lorem ipsum dolor sit amet, consectetur  incididunt ut labore et dolore magna aliqua Ut enim ad minim veniam quis nostrud.`,
  },
  {
    id: 4,
    title: 'Weddings',
    category: 'Catering Orders',
    price: 699.99,
    img: './images/image-2.jpeg',
    desc: `Lorem ipsum dolor sit amet, consectetur  incididunt ut labore et dolore magna aliqua Ut enim ad minim veniam quis nostrud. `,
  },
  {
    id: 5,
    title: 'Meal Combo 3',
    category: 'lunch',
    price: 22.99,
    img: './images/image-1.jpeg',
    desc: `Lorem ipsum dolor sit amet, consectetur  incididunt ut labore et dolore magna aliqua Ut enim ad minim veniam quis nostrud. `,
  },
  {
    id: 6,
    title: 'Reception',
    category: 'Catering Orders',
    price: 499.99,
    img: './images/image-2.jpeg',
    desc: `Lorem ipsum dolor sit amet, consectetur  incididunt ut labore et dolore magna aliqua Ut enim ad minim veniam quis nostrud. `,
  },
  {
    id: 7,
    title: 'Meal Combo 4',
    category: 'lunch',
    price: 12.99,
    img: './images/image-1.jpeg',
    desc: `Lorem ipsum dolor sit amet, consectetur  incididunt ut labore et dolore magna aliqua Ut enim ad minim veniam quis nostrud. `,
  },
  {
    id: 8,
    title: 'Corporate',
    category: 'Catering Orders',
    price: 399.99,
    img: './images/image-2.jpeg',
    desc: `Lorem ipsum dolor sit amet, consectetur  incididunt ut labore et dolore magna aliqua Ut enim ad minim veniam quis nostrud. `,
  },
];
export default menu;
